### PR TITLE
Persist membership cache between requests

### LINKED ISSUE #52: Membership data not being cached between requests
It looks like the membership data that is supposed to be cached between requests for 5 minutes is not being cached at all.

It looks like it was assumed that the `User` object would be serialized after each request, storing the modified membership cache in the session. Turns out that the user is only serialized once from `Warden::Proxy#set_user` that gets called when authentication is successfully performed the first time.

The solution would be to store the membership data (more precisely, any data potentially changing between requests) in `Warden::Proxy#session`, which "provides a scoped session data for authenticated users". In order to have access to that scoped session data, the `User` object needs to receive it at time of first initialization and deserialization. It can be retrieved from warden as follows (in both situations `env` is available): `env['warden'].session(scope)`

I'll open a PR for this. @atmos since this will need a minor version bump, should I already include it in the PR or would you like to handle that separately?

### PR DESCRIPTION
**Pull request by fphilipe**
The membership cache was being serialized into the user object. It was assumed that the user object was serialized at the end of each request. It turns out that this is not the case. Instead, the user object only gets serialized once, namely after setting the user. This means that the membership cache wasn't working at all between requests.

This commit fixes it by not including the memberships in the serialized user as there's no point in doing so. Instead, after the user object is set up, the memberships hash get retrieved from the user session (warden provides a session object for each scope; if there is none, a new hash is stored in the session) and assigned to the user object. The hash is
then used as before and we get the session serialization from rack for free.

Fixes #52.

### CODE REVIEW

**Comment by atmos** [comment]
Hi @fphilipe,

Any idea what's up with the rack error? I think this was something common in upgrades like 2-3 years ago.

**Comment by fphilipe** [comment]
Hey @atmos. Do you mean rack or rake? 😊 The error in the build is fixed by my other PR. I'd rebase this PR on top of the other once that one is merged, or I can combine them into one PR, as you prefer.

Also, I just bumped the patch version number, since this change is completely backwards compatible. The old serialization format that included the `memberships` field of the struct would still deserialize correctly.

**Comment by atmos** [comment]
1.3.2 is live on rubygems.org

**Comment by fphilipe** [comment]
Thanks @atmos!

**Pull request merged**
